### ISSUE TITLE
Don't store Cucumber JARs

### ISSUE THREAD

**Issue by echebbi** [pitest/pitclipse#103]
## Motivation

Storing bare JARs inside the Git repository makes harder to upgrade dependencies.

## Proposed Solution

Pitest's JARs have recently been removed from the repository (see issue #99, fixed by PR #101); the same approach should work for Cucumber's JARs.

**Comment by LorenzoBettini** [comment]
I was about to open such issue myself ;)
Do you need help on this?

**Comment by echebbi** [comment]
I think I should be able to follow your example to fix this, thank you
