### ISSUE TITLE
Switch from Bintray to GitHub Pages for serving the Eclipse update site

### ISSUE THREAD

**Issue by LorenzoBettini** [pitest/pitclipse#122]
## Motivation

Bintray is shutting down, so we cannot serve the Eclipse update site from there...

## Proposed Solution

I suggest we switch to GitHub Pages for the Eclipse (composite) update site. I already have a working example for that. This requires creating a new GitHub repository for hosting the update site (@hcoles, @echebbi I think I can create that myself in the organization with my admin rights). While hosting binaries on GitHub pages is not ideal, I don't foresee a lot of traffic so we should be fine (and in my experiments, it's pretty fast).

By the way, Bintray is shutting down really soon (I guess the end of March), so we should act pretty quickly.

**Comment by LorenzoBettini** [comment]
> We'll also have to update the link to the update site in the Eclipse Marketplace entry. By the way I can grant you the rights to edit the entry if you give me your Eclipse UID.

You mean my Eclipse email address? It's the one in the commits lorenzo.bettini gmail 

> 
> Do we really need an additional repository? We can merely create a dedicated branch to host binaries, can't we?

We could, but that would make the main repository heavyweight that's why I'd avoid that (not to mention that we might hit the GitHub limitations if we store the update sites in the same repository of the main code) ;)
The experiments are making are based on another GitHub repository and I found that procedure much easier (the publishing is done during the Maven/Tycho build by the way)

**Comment by echebbi** [comment]
> You mean my Eclipse email address? It's the one in the commits lorenzo.bettini gmail

Yeah, looks like your email address was enough, you should have the rights now.

> We could, but that would make the main repository heavyweight that's why I'd avoid that (not to mention that we might hit the GitHub limitations if we store the update sites in the same repository of the main code) ;)

Understood, makes sense!

> The experiments are making are based on another GitHub repository and I found that procedure much easier (the publishing is done during the Maven/Tycho build by the way)

Great, thank you. I think we should also take the opportunity to automate the deployment through GitHub Actions (e.g. each time a tag is pushed to master).

For the record here are some deployment-specific stuff that should be removed:
 - the [_.travis/build.sh_](https://github.com/pitest/pitclipse/blob/06fa7cd/.travis/build.sh) script
 - the [_release-composite_](https://github.com/pitest/pitclipse/blob/24ccae8615d9af135681fa70596789e437fb23cb/releng/org.pitest.pitclipse.p2/pom.xml#L35-L134) Maven profile (or rather adapt it to publish to GitHub Pages instead),
 - the [_bintray.ant_](https://github.com/pitest/pitclipse/blob/cd9a768/releng/org.pitest.pitclipse.p2/bintray.ant) script,
 - the [_removeFromBintray.sh_](https://github.com/pitest/pitclipse/blob/cd9a768/releng/org.pitest.pitclipse.p2/removeFromBintray.sh) script.

**Comment by ebramirez** [comment]
Hi @LorenzoBettini and @echebbi,

How is this moving along?
The update site is no longer responding.

**Comment by echebbi** [comment]
I have a bit of free time this week so I should be able to tackle this.

@LorenzoBettini I don't have the rights to create a new repository in the _pitest_ organization, can you create it?

**Comment by LorenzoBettini** [comment]
@echebbi I don't have it either :(

Maybe @hcoles can create that or can give us the rights to do that?

I might have some free time from this Friday, please let me know if I can do anything.

Remember that first we should:

- merge the branch where Jupiter support has been added
- use reproducible build qualifiers in version numbers

**Comment by echebbi** [comment]
> Remember that first we should:
> - merge the branch where Jupiter support has been added
> - use reproducible build qualifiers in version numbers

I'll do that tonight. I may also have the time to work on the deployment to GitHub Pages; can I proceed or are you already doing things on your side?

**Comment by echebbi** [comment]
@LorenzoBettini I updated the POM files to automate the deployment of a composite update site to a GitHub repository. I didn't try to actually deploy the p2 repo but `mvn verify -P release-composite` seems to create the update site as expected. The GitHub Actions are still missing and I won't have time for that before tomorrow so feel free to take over if you have some free time today.

My current work is on the _120-deploy-to-github-pages_ branch.

**Comment by LorenzoBettini** [comment]
Hi, I can work on parallel things today. I can take care of GitHub Actions workflow. I'll also review your changes. There's still to configure the two additional GitHub repositories to serve GitHub Pages from the `master` branch.

**Comment by echebbi** [comment]
> I can take care of GitHub Actions workflow. I'll also review your changes

Great, thank you!

> There's still to configure the two additional GitHub repositories to serve GitHub Pages from the master branch.

I just took care of it, should be working now.

**Comment by LorenzoBettini** [comment]
OK!
So we now have the new update site https://pitest.github.io/pitclipse-releases/
and the MarketPlace entry has been updated as well!
Happy mutation testing! :)

**Comment by ebramirez** [comment]
Thanks a lot @LorenzoBettini @echebbi!
