### ISSUE TITLE
Upgrade Pitest version

### ISSUE THREAD

**Issue by echebbi** [pitest/pitclipse#123]
## Motivation

Looks like we missed a few Pitest releases. At the time of writing the latest is [1.6.6](https://search.maven.org/artifact/org.pitest/pitest/1.6.6/jar) whereas we're still using Pitest 1.4.11

## Proposed Solution

Upgrade the version used in [bundles/org.pitest/pom.xml](../blob/master/bundles/org.pitest/pom.xml) and [features/org.pitest.feature/feature.xml](../blob/master/features/org.pitest.feature/feature.xml).

Make sure Pitclipse still compiles and doesn't suffer any regression.

**Comment by LorenzoBettini** [comment]
Once #134 has been merged (and we thus have UI tests) I can work on this and upgrade PIT to the latest release

**Comment by JKutscha** [comment]
Hi @LorenzoBettini, now that you can merge #134, will you work on this matter or did you already upgrade the pit version and haven't updated it yet?

**Comment by LorenzoBettini** [comment]
@JKutscha I still haven't upgraded PIT but I'll try to do that ASAP
