### ISSUE TITLE
Maven requirements aren't correct

### ISSUE THREAD

**Issue by JKutscha** [pitest/pitclipse#138]
## Bug description
The requirements lists Maven 3.x, but you can't use it with Maven 3.0.5.

## How to reproduce

1. Install Maven 3.0.5
2. Run mvn or mvn clean verify in the main folder 

## Fix
Just update the README requirements to Maven 3.1.x or higher perhaps?

**Comment by LorenzoBettini** [comment]
@JKutscha could you please be more specific on the error you get?
In any case, for sure Maven 3.0.5 is rather old. I think at least Maven 3.6.3 is required.
Of course, if you don't mind, please feel free to create a PR for the README :)

**Comment by JKutscha** [comment]
The error is the following:

/home/pitclipse[master]$ mvn -e                                                                                                                                                                                                                                    
[INFO] Error stacktraces are turned on.                                                                                                                                                                                                                                                   
[INFO] Scanning for projects...                                                                                                                                                                                                                                                           
[ERROR] The build could not read 2 projects -> [Help 1]                                                                                                                                                                                                                                   
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:                                                                                                                                                                              
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.core/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @                                                                                                                              
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.launch/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @                                                                                                                            
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.launch.ui/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @                                                                                                                         
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.listeners/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @                                                                                                                         
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.preferences.ui/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @                                                                                                                    
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.runner/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @                                                                                                                            
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.ui/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @                                                                                                                                
[ERROR] Child module /home/pitclipse/features/org.pitest.feature/pom.xml of /home/pitclipse/features/pom.xml does not exist @                                                                                                                                   
[ERROR] Child module /home/pitclipse/features/org.pitest.pitclipse.core.feature/pom.xml of /home/pitclipse/features/pom.xml does not exist @                                                                                                                    
[ERROR] Child module /home/pitclipse/features/org.pitest.pitclipse.ui.feature/pom.xml of /home/pitclipse/features/pom.xml does not exist @                                                                                                                      
                                                                                                                                                                                                                                                                                          
        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)                                                                                                                                                                                           
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)                                                                                                                                                                                                           
        at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)                                                                                                                                                                                                
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)                                                                                                                                                                                                                 
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[ERROR]   
[ERROR]   The project org.pitest:org.pitest.pitclipse.bundles:2.1.2-SNAPSHOT (/home/pitclipse/bundles/pom.xml) has 7 errors
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.core/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.launch/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.launch.ui/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.listeners/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.preferences.ui/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.runner/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.ui/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]   
[ERROR]   The project org.pitest:org.pitest.pitclipse.features:2.1.2-SNAPSHOT (/home/pitclipse/features/pom.xml) has 3 errors
[ERROR]     Child module /home/pitclipse/features/org.pitest.feature/pom.xml of /home/pitclipse/features/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/features/org.pitest.pitclipse.core.feature/pom.xml of /home/pitclipse/features/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/features/org.pitest.pitclipse.ui.feature/pom.xml of /home/pitclipse/features/pom.xml does not exist
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException


/home/pitclipse[master]$ mvn -X
Apache Maven 3.0.5 (Red Hat 3.0.5-17)
Maven home: /usr/share/maven
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.181-3.b13.el7_5.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-862.3.2.el7.x86_64", arch: "amd64", family: "unix"
[INFO] Error stacktraces are turned on.
[DEBUG] Reading global settings from /usr/share/maven/conf/settings.xml
[DEBUG] Reading user settings from /home/USER/.m2/settings.xml
[DEBUG] Using local repository at /home/USER/.m2/repository
[DEBUG] Using manager EnhancedLocalRepositoryManager with priority 10 for /home/USER/.m2/repository
[INFO] Scanning for projects...
[DEBUG] org.eclipse.tycho:tycho-maven-plugin:jar:1.7.0:
[DEBUG]    org.eclipse.tycho:tycho-core:jar:1.7.0:compile
[DEBUG]       org.apache.maven:maven-core:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-model:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-settings:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-settings-builder:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-repository-metadata:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-artifact:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-model-builder:jar:3.0:compile
[DEBUG]          org.apache.maven:maven-aether-provider:jar:3.0:runtime
[DEBUG]          org.sonatype.aether:aether-impl:jar:1.7:compile
[DEBUG]             org.sonatype.aether:aether-spi:jar:1.7:compile
[DEBUG]          org.sonatype.aether:aether-api:jar:1.7:compile
[DEBUG]          org.sonatype.aether:aether-util:jar:1.7:compile
[DEBUG]          org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2:compile
[DEBUG]             org.sonatype.sisu:sisu-inject-bean:jar:1.4.2:compile
[DEBUG]                org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7:compile
[DEBUG]          org.codehaus.plexus:plexus-interpolation:jar:1.14:compile
[DEBUG]          org.codehaus.plexus:plexus-classworlds:jar:2.2.3:compile
[DEBUG]          org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]             org.sonatype.plexus:plexus-cipher:jar:1.7:compile (version managed from 1.4)
[DEBUG]       org.apache.maven:maven-plugin-api:jar:3.0:compile
[DEBUG]       org.eclipse.tycho:org.eclipse.tycho.p2.tools.shared:jar:1.7.0:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:3.3.0:compile
[DEBUG]       org.codehaus.plexus:plexus-archiver:jar:4.2.2:compile
[DEBUG]          org.codehaus.plexus:plexus-io:jar:3.2.0:compile
[DEBUG]             commons-io:commons-io:jar:2.6:compile
[DEBUG]          org.apache.commons:commons-compress:jar:1.20:compile
[DEBUG]          org.iq80.snappy:snappy:jar:0.4:compile
[DEBUG]          org.tukaani:xz:jar:1.8:runtime
[DEBUG]       org.eclipse.platform:org.eclipse.osgi.compatibility.state:jar:1.1.700:compile
[DEBUG]          org.eclipse.platform:org.eclipse.osgi:jar:3.15.200:compile (version managed from [3.12.0,))
[DEBUG]       org.eclipse.tycho:sisu-equinox-embedder:jar:1.7.0:compile
[DEBUG]          org.eclipse.tycho:sisu-equinox-api:jar:1.7.0:compile
[DEBUG]       org.eclipse.tycho:tycho-metadata-model:jar:1.7.0:compile
[DEBUG]          de.pdark:decentxml:jar:1.4:compile
[DEBUG]       org.eclipse.tycho:tycho-embedder-api:jar:1.7.0:compile
[DEBUG]          org.eclipse.tycho:org.eclipse.tycho.embedder.shared:jar:1.7.0:compile
[DEBUG]       org.eclipse.tycho:org.eclipse.tycho.core.shared:jar:1.7.0:compile
[DEBUG]       org.apache.maven:maven-compat:jar:3.0:compile
[DEBUG]          org.apache.maven.wagon:wagon-provider-api:jar:1.0-beta-6:compile
[DEBUG]    org.eclipse.tycho:tycho-p2-facade:jar:1.7.0:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.7.1:compile
[DEBUG]       org.eclipse.tycho:org.eclipse.tycho.p2.resolver.shared:jar:1.7.0:compile
[DEBUG] Created new class realm maven.api
[DEBUG] Importing foreign packages into class realm maven.api
[DEBUG]   Imported: org.apache.maven.cli < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.lifecycle < plexus.core
[DEBUG]   Imported: org.apache.maven.repository < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.personality < plexus.core
[DEBUG]   Imported: org.apache.maven.usability < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.configuration < plexus.core
[DEBUG]   Imported: org.sonatype.aether.version < plexus.core
[DEBUG]   Imported: org.sonatype.aether.* < plexus.core
[DEBUG]   Imported: org.sonatype.aether.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.* < plexus.core
[DEBUG]   Imported: org.apache.maven.project < plexus.core
[DEBUG]   Imported: org.sonatype.aether.repository < plexus.core
[DEBUG]   Imported: org.sonatype.aether.impl < plexus.core
[DEBUG]   Imported: org.apache.maven.exception < plexus.core
[DEBUG]   Imported: org.apache.maven.plugin < plexus.core
[DEBUG]   Imported: org.sonatype.aether.collection < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.* < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.logging < plexus.core
[DEBUG]   Imported: org.apache.maven.profiles < plexus.core
[DEBUG]   Imported: org.sonatype.aether.metadata < plexus.core
[DEBUG]   Imported: org.sonatype.aether.spi < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParserException < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.* < plexus.core
[DEBUG]   Imported: org.sonatype.aether.graph < plexus.core
[DEBUG]   Imported: org.apache.maven.rtinfo < plexus.core
[DEBUG]   Imported: org.sonatype.aether.installation < plexus.core
[DEBUG]   Imported: org.apache.maven.monitor < plexus.core
[DEBUG]   Imported: org.sonatype.aether.transfer < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.context < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.observers < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.resource < plexus.core
[DEBUG]   Imported: org.sonatype.aether.deployment < plexus.core
[DEBUG]   Imported: org.apache.maven.model < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.Xpp3Dom < plexus.core
[DEBUG]   Imported: org.apache.maven.artifact < plexus.core
[DEBUG]   Imported: org.apache.maven.toolchain < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlSerializer < plexus.core
[DEBUG]   Imported: org.apache.maven.settings < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authorization < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.events < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.authentication < plexus.core
[DEBUG]   Imported: org.apache.maven.reporting < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.repository < plexus.core
[DEBUG]   Imported: org.apache.maven.configuration < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.classworlds < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.util.xml.pull.XmlPullParser < plexus.core
[DEBUG]   Imported: org.apache.maven.classrealm < plexus.core
[DEBUG]   Imported: org.sonatype.aether.resolution < plexus.core
[DEBUG]   Imported: org.apache.maven.execution < plexus.core
[DEBUG]   Imported: org.apache.maven.wagon.proxy < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.container < plexus.core
[DEBUG]   Imported: org.codehaus.plexus.component < plexus.core
[DEBUG] Populating class realm maven.api
[DEBUG] Created new class realm extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0
[DEBUG] Importing foreign packages into class realm extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0
[DEBUG]   Imported:  < maven.api
[DEBUG] Populating class realm extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0
[DEBUG]   Included: org.eclipse.tycho:tycho-maven-plugin:jar:1.7.0
[DEBUG]   Included: org.eclipse.tycho:tycho-core:jar:1.7.0
[DEBUG]   Included: org.sonatype.aether:aether-util:jar:1.7
[DEBUG]   Included: org.sonatype.sisu:sisu-inject-bean:jar:1.4.2
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.14
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.7
[DEBUG]   Included: org.eclipse.tycho:org.eclipse.tycho.p2.tools.shared:jar:1.7.0
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.3.0
[DEBUG]   Included: org.codehaus.plexus:plexus-archiver:jar:4.2.2
[DEBUG]   Included: org.codehaus.plexus:plexus-io:jar:3.2.0
[DEBUG]   Included: commons-io:commons-io:jar:2.6
[DEBUG]   Included: org.apache.commons:commons-compress:jar:1.20
[DEBUG]   Included: org.iq80.snappy:snappy:jar:0.4
[DEBUG]   Included: org.tukaani:xz:jar:1.8
[DEBUG]   Included: org.eclipse.platform:org.eclipse.osgi.compatibility.state:jar:1.1.700
[DEBUG]   Included: org.eclipse.platform:org.eclipse.osgi:jar:3.15.200
[DEBUG]   Included: org.eclipse.tycho:sisu-equinox-embedder:jar:1.7.0
[DEBUG]   Included: org.eclipse.tycho:sisu-equinox-api:jar:1.7.0
[DEBUG]   Included: org.eclipse.tycho:tycho-metadata-model:jar:1.7.0
[DEBUG]   Included: de.pdark:decentxml:jar:1.4
[DEBUG]   Included: org.eclipse.tycho:tycho-embedder-api:jar:1.7.0
[DEBUG]   Included: org.eclipse.tycho:org.eclipse.tycho.embedder.shared:jar:1.7.0
[DEBUG]   Included: org.eclipse.tycho:org.eclipse.tycho.core.shared:jar:1.7.0
[DEBUG]   Included: org.eclipse.tycho:tycho-p2-facade:jar:1.7.0
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.7.1
[DEBUG]   Included: org.eclipse.tycho:org.eclipse.tycho.p2.resolver.shared:jar:1.7.0
[DEBUG] Extension realms for project org.pitest:org.pitest.pitclipse:pom:2.1.2-SNAPSHOT: [ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0, parent: sun.misc.Launcher$AppClassLoader@70dea4e]]
[DEBUG] Created new class realm project>org.pitest:org.pitest.pitclipse:2.1.2-SNAPSHOT
[DEBUG] Populating class realm project>org.pitest:org.pitest.pitclipse:2.1.2-SNAPSHOT
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[project>org.pitest:org.pitest.pitclipse:2.1.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[DEBUG] Extension realms for project org.pitest:org.pitest.pitclipse.bundles:pom:2.1.2-SNAPSHOT: [ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0, parent: sun.misc.Launcher$AppClassLoader@70dea4e]]
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[project>org.pitest:org.pitest.pitclipse:2.1.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[DEBUG] Extension realms for project org.pitest:org.pitest.pitclipse.features:pom:2.1.2-SNAPSHOT: [ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0, parent: sun.misc.Launcher$AppClassLoader@70dea4e]]
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[project>org.pitest:org.pitest.pitclipse:2.1.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[DEBUG] Extension realms for project org.pitest:org.pitest.pitclipse.releng:pom:2.1.2-SNAPSHOT: [ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0, parent: sun.misc.Launcher$AppClassLoader@70dea4e]]
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[project>org.pitest:org.pitest.pitclipse:2.1.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[DEBUG] Extension realms for project org.pitest:org.pitest.pitclipse.target:eclipse-target-definition:2.1.2-SNAPSHOT: [ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0, parent: sun.misc.Launcher$AppClassLoader@70dea4e]]
[DEBUG] Looking up lifecyle mappings for packaging eclipse-target-definition from ClassRealm[project>org.pitest:org.pitest.pitclipse:2.1.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[DEBUG] Extension realms for project org.pitest:org.pitest.pitclipse.p2:eclipse-repository:2.1.2-SNAPSHOT: [ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0, parent: sun.misc.Launcher$AppClassLoader@70dea4e]]
[DEBUG] Looking up lifecyle mappings for packaging eclipse-repository from ClassRealm[project>org.pitest:org.pitest.pitclipse:2.1.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[DEBUG] Extension realms for project org.pitest:org.pitest.pitclipse.tests:pom:2.1.2-SNAPSHOT: [ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0, parent: sun.misc.Launcher$AppClassLoader@70dea4e]]
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[project>org.pitest:org.pitest.pitclipse:2.1.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[DEBUG] Extension realms for project org.pitest:org.pitest.pitclipse.runner.tests:eclipse-test-plugin:2.1.2-SNAPSHOT: [ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0, parent: sun.misc.Launcher$AppClassLoader@70dea4e]]
[DEBUG] Looking up lifecyle mappings for packaging eclipse-test-plugin from ClassRealm[project>org.pitest:org.pitest.pitclipse:2.1.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[DEBUG] Extension realms for project org.pitest:io.cucumber:eclipse-plugin:4.3.0: [ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0, parent: sun.misc.Launcher$AppClassLoader@70dea4e]]
[DEBUG] Looking up lifecyle mappings for packaging eclipse-plugin from ClassRealm[project>org.pitest:org.pitest.pitclipse:2.1.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[DEBUG] Extension realms for project org.pitest:org.pitest.pitclipse.tests.coverage.report:pom:2.1.2-SNAPSHOT: [ClassRealm[extension>org.eclipse.tycho:tycho-maven-plugin:1.7.0, parent: sun.misc.Launcher$AppClassLoader@70dea4e]]
[DEBUG] Looking up lifecyle mappings for packaging pom from ClassRealm[project>org.pitest:org.pitest.pitclipse:2.1.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]
[ERROR] The build could not read 2 projects -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.core/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @ 
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.launch/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @ 
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.launch.ui/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @ 
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.listeners/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @ 
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.preferences.ui/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @ 
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.runner/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @ 
[ERROR] Child module /home/pitclipse/bundles/org.pitest.pitclipse.ui/pom.xml of /home/pitclipse/bundles/pom.xml does not exist @ 
[ERROR] Child module /home/pitclipse/features/org.pitest.feature/pom.xml of /home/pitclipse/features/pom.xml does not exist @ 
[ERROR] Child module /home/pitclipse/features/org.pitest.pitclipse.core.feature/pom.xml of /home/pitclipse/features/pom.xml does not exist @ 
[ERROR] Child module /home/pitclipse/features/org.pitest.pitclipse.ui.feature/pom.xml of /home/pitclipse/features/pom.xml does not exist @ 

        at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)
        at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
        at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[ERROR]   
[ERROR]   The project org.pitest:org.pitest.pitclipse.bundles:2.1.2-SNAPSHOT (/home/pitclipse/bundles/pom.xml) has 7 errors
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.core/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.launch/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.launch.ui/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.listeners/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.preferences.ui/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.runner/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/bundles/org.pitest.pitclipse.ui/pom.xml of /home/pitclipse/bundles/pom.xml does not exist
[ERROR]   
[ERROR]   The project org.pitest:org.pitest.pitclipse.features:2.1.2-SNAPSHOT (/home/pitclipse/features/pom.xml) has 3 errors
[ERROR]     Child module /home/pitclipse/features/org.pitest.feature/pom.xml of /home/pitclipse/features/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/features/org.pitest.pitclipse.core.feature/pom.xml of /home/pitclipse/features/pom.xml does not exist
[ERROR]     Child module /home/pitclipse/features/org.pitest.pitclipse.ui.feature/pom.xml of /home/pitclipse/features/pom.xml does not exist
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

**Comment by LorenzoBettini** [comment]
OK, that's probably due to Tycho POMless build that was not supported with earlier versions of Maven

**Comment by LorenzoBettini** [comment]
Closed by #141 

Thanks!
