### ISSUE TITLE
Unable to install via Eclipse

### ISSUE THREAD

**Issue by BenjaminGroseclose** [pitest/pitclipse#189]
## Bug description

Unable to install Pitclipse via Eclipse Marketplace
![image](https://user-images.githubusercontent.com/21026775/154392453-ec74576f-31ec-4d35-a9f8-62b8bdcc70c9.png)

## Expected behavior

To be able to install via the Eclipse Marketplace

## How to reproduce

1. Go to `Help` -> `Eclipse Marketplace`
2. Search for `pitclipse`
3. Click on install

## Additional context

- **Pitclipse version**: `2.1.2`
- **Eclipse IDE version**: `2021-12 (4.22.0)`

**Comment by LorenzoBettini** [comment]
It might be a temporary network problem... can you please try again?

**Comment by BenjaminGroseclose** [comment]
Still am seeing the same issue.

**Comment by justin-firestone** [comment]
I am encountering this issue but still cannot install when I check to contact all update sites. Is there a specific link to the guava libraries I should add to my list of sites?

**Comment by LorenzoBettini** [comment]
Doesn't it find guava at all or the specific required version?

**Comment by justin-firestone** [comment]
I get the exact same error message you received from your screenshot.

I'm not familiar with building Eclipse plugins. Is there a way to download the guava library and include it in a build path locally? I tried that by downloading the .jar and adding the local directory for it, but still the same error message.
________________________________

**Comment by LorenzoBettini** [comment]
Before installing pitclipse in eclipse, you can manually add this update site https://download.eclipse.org/tools/orbit/downloads/2021-06/ and guava will be found with the required version.

**Comment by MahatmaFatalError** [comment]
> [download.eclipse.org/tools/orbit/downloads/2021-06](https://download.eclipse.org/tools/orbit/downloads/2021-06/)

Before that I got
```
An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.google.guava,21.0.0.v20170206-1425
No repository found containing: osgi.bundle,com.sun.xml.bind,2.2.0.v201505121915
```


Now I get
```
An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,com.sun.xml.bind,2.2.0.v201505121915
```

Pitclipse 2.1.2
Spring STS 4.15.1.RELEASE -> Eclipse 4.24.0

**Comment by LorenzoBettini** [comment]
OK, I'll try to take a look at this ASAP

**Comment by LorenzoBettini** [comment]
It's fixed now!
You don't have to add manually the orbit update site.
I tested the installation of 2.2.0 both in Eclipse Java and Eclipse STS, both from the update site and from the Marketplace.
Thanks for your patience :)

**Comment by MahatmaFatalError** [comment]
Big Thanks!
