### ISSUE TITLE
Icons for navigation in PIT Summary view

### ISSUE THREAD

**Issue by LorenzoBettini** [pitest/pitclipse#201]
Currently, we don't have icons for the navigation buttons in the summary view

![image](https://user-images.githubusercontent.com/1202254/183417253-38fb350a-6316-4ab5-a6f9-138cb8e7b413.png)

**Comment by LorenzoBettini** [comment]
We could use some of the browser's icons

![image](https://user-images.githubusercontent.com/1202254/183418646-7279e807-4e3f-47f7-bed1-702494465085.png)

**Comment by LorenzoBettini** [comment]
I created the PR #202 that's the result

![image](https://user-images.githubusercontent.com/1202254/186156840-4ea5c956-96fb-437e-a3c9-c8b7d191301d.png)

@echebbi @JKutscha what do you think?

I also changed the tooltips from "<", ">" to "Back" and "Forward"

**Comment by JKutscha** [comment]
@LorenzoBettini Looks great. Thanks.

**Comment by LorenzoBettini** [comment]
@JKutscha thanks for the feedback: I'm merging...
