### ISSUE TITLE
icon of UX label in bug tracker broken

### ISSUE THREAD

**Issue by Bananeweizen** [pitest/pitclipse#214]
The issue label for UX issues is broken. Most labels in the issue tracker have an emoticon embedded, and the "blonde_man" in the UX label seems to be gone, that's why it is not rendered in the link in the next line:
https://github.com/pitest/pitclipse/labels/impacts%3A%20ux%20%3Ablonde_man%3A

**Comment by LorenzoBettini** [comment]
I've just replaced that with a smile... if you have a better suggestion we can re-open this ;)
thanks!
