### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character 3c

### ISSUE THREAD

**Issue by john-h-robb** [pitest/pitclipse#222]
## Bug description

Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character 3c

## Expected behavior

When I try to run Pitclipse in Eclipse 2023-06

## Additional context

- **Pitclipse version**:
- **Eclipse IDE version**:

**Comment by LorenzoBettini** [comment]
Without further information or an example to reproduce the problem, I think I'll close this...

**Comment by john-h-robb** [comment]
what example do you need? This is when I select any Junit Test file and attempt to run with Pitclipse. I can get PIT to work from the command line but would prefer an embedded Eclipse solution
    On Saturday, February 3, 2024 at 10:03:44 AM CST, Lorenzo Bettini ***@***.***> wrote:  
 
 


Without further information or an example to reproduce the problem, I think I'll close this...

**Comment by john-h-robb** [comment]
Here is the longer error message:

10:17:17 AM PIT >> FINE : Coverage generator Minion exited ok

10:17:17 AM PIT >> INFO : Calculated coverage in 0 seconds.

10:17:17 AM PIT >> FINE : Used memory after coverage calculation 42 mb

10:17:17 AM PIT >> FINE : Free Memory after coverage calculation 213 mb

Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character 3c

 at java.base/java.util.Base64$Decoder.decode0(Base64.java:848)

 at java.base/java.util.Base64$Decoder.decode(Base64.java:566)

 at java.base/java.util.Base64$Decoder.decode(Base64.java:589)

 at org.pitest.mutationtest.incremental.ObjectOutputStreamHistoryStore.deserialize(ObjectOutputStreamHistoryStore.java:124)

 at org.pitest.mutationtest.incremental.ObjectOutputStreamHistoryStore.restoreClassPath(ObjectOutputStreamHistoryStore.java:112)

 at org.pitest.mutationtest.incremental.ObjectOutputStreamHistoryStore.initialize(ObjectOutputStreamHistoryStore.java:84)

 at org.pitest.mutationtest.tooling.MutationCoverage.runAnalysis(MutationCoverage.java:159)

 at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:139)

 at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:125)

 at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:52)

 at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)

 at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)

 at org.pitest.pitclipse.runner.PitRunner.apply(PitRunner.java:35)

 at org.pitest.pitclipse.runner.PitRunner.apply(PitRunner.java:1)

 at java.base/java.util.Optional.map(Optional.java:260)

 at org.pitest.pitclipse.runner.PitRunnerMain.main(PitRunnerMain.java:38)




    On Saturday, February 3, 2024 at 10:14:54 AM CST, John Robb ***@***.***> wrote:  
 
  The JDK I am using is Eclipse Adoptium 21.0.2.13.
The file works with JUnit 4 and with EclEmma 3.1.7.2023... and gets complete coverage
    On Saturday, February 3, 2024 at 10:10:11 AM CST, Lorenzo Bettini ***@***.***> wrote:  
 
 


Java version, project encoding, etc.

**Comment by john-h-robb** [comment]
And the version of Pitclipse is shown here: 0839;C:\Users\Owner_2\.p2\pool\plugins\org.pitest.pitclipse.runner_2.2.1.v20230330-

10:19:22 AM PIT >> FINE : Running report with ReportOptions [targetClasses=[Homework3.Problem2Class$RollProgram, Homework3.Problem4Class$Status, Homework5.Problem2Class$gDoorStates, Homework5.Problem3Class, Homework4.Problem3ClassTest, Homework4.Problem4Class, Homework3.Problem3ClassTest, Homework5.Problem1ClassTest, Homework5.Problem4ClassTest, Homework3.Problem2Class$RRPvals, Homework3.Problem5Class, Homework4.Problem2Class$RRPvals, Homework5.Problem2CORRECTEDClassTest, Homework3.Problem4aClass, Homework4.Problem3Class, Homework5.Problem2Class, Homework4.Problem3Class$landingState, Homework4.Problem4Class$Status, Homework5.Problem3ClassTest, Homework4.Problem4ClassTest, Homework5.Problem5ServerData, Homework3.Problem5ClassTest, Homework3.Problem3Class2, Homework5.Problem4Class, Homework3.Problem3Class$landingState, Homework5.Problem1Class, Homework5.Problem1Class$motorStates, Homework4.Problem2Class$RollProgram, Homework3.Problem3Class, Homework3.Problem4aClassTest2, Homework3.Problem4aClass$Status, Homework3.Problem1ClassTest, Homework5.Problem2ClassTest, Homework5.Problem5ClassTest, Homework3.Problem2Class, Homework4.Problem1Class, Homework3.Problem4ClassTest, Homework4.Problem2ClassTest, Homework4.Problem5ClassTest, Homework3.Problem3Class2$landingState, Homework5.Problem2CORRECTEDClass, Homework5.Problem5Class, Homework3.Problem2Class$Pods, Homework3.Problem4Class, Homework5.Problem2CORRECTEDClass$gDoorStates, Homework3.Problem1Class, Homework3.Problem5Graph, Homework4.Problem2Class$Pods, Homework4.Problem5Class, Homework4.Problem2Class, Homework4.Problem1ClassTest, Homework3.Problem2ClassTest], excludedMethods=[], excludedClasses=[*Test], excludedTestClasses=[], codePaths=[], reportDir=\\DISKSTATION\Family_Folder\John\Eclipse workspace\.metadata\.plugins\org.pitest.pitclipse.core\html_results, historyInputLocation=\\DISKSTATION\Family_Folder\John\Eclipse workspace\.metadata\.plugins\org.pitest.pitclipse.core\history\state-1.1.0.out, historyOutputLocation=\\DISKSTATION\Family_Folder\John\Eclipse workspace\.metadata\.plugins\org.pitest.pitclipse.core\history\state-1.1.0.out, sourceDirs=[\\DISKSTATION\Family_Folder\John\Eclipse workspace\CSE 5321 2020 Fall\src], classPathElements=[C:\Users\Owner_2\.p2\pool\plugins\org.pitest_1.6.8.v20230330-0839, C:\Users\Owner_2\.p2\pool\plugins\org.pitest.pitclipse.runner_2.2.1.v20230330-0839.jar, C:\Users\Owner_2\.p2\pool\plugins\org.pitest.pitclipse.runner_2.2.1.v20230330-0839.jar\target\classes, C:\Users\Owner_2\.p2\pool\plugins\org.pitest_1.6.8.v20230330-0839\lib\pitest.jar, C:\Users\Owner_2\.p2\pool\plugins\org.pitest_1.6.8.v20230330-0839\lib\pitest-entry.jar, C:\Users\Owner_2\.p2\pool\plugins\org.pitest_1.6.8.v20230330-0839\lib\pitest-command-line.jar, C:\Users\Owner_2\.p2\pool\plugins\org.pitest_1.6.8.v20230330-0839\lib\pitest-html-report.jar, C:\Users\Owner_2\.p2\pool\plugins\org.pitest.pitclipse.listeners_2.2.1.v20230330-0839.jar, C:\Users\Owner_2\.p2\pool\plugins\org.pitest.pitclipse.listeners_2.2.1.v20230330-0839.jar\target\classes, \\DISKSTATION\Family_Folder\John\Eclipse workspace\CSE 5321 2020 Fall\bin, C:\Users\Owner_2\.p2\pool\plugins\org.junit_4.13.2.v20211018-1956.jar, C:\Users\Owner_2\.p2\pool\plugins\org.hamcrest.core_1.3.0.v20180420-1519.jar, \\DISKSTATION\Family_Folder\John\Eclipse workspace\JUnitParams-1.0.4.jar, \\DISKSTATION\Family_Folder\John\Eclipse workspace\easymock-3.4.jar], mutators=[STRONGER], features=[], dependencyAnalysisMaxDistance=-1, jvmArgs=[-Djava.awt.headless=true], numberOfThreads=8, timeoutFactor=1.25, timeoutConstant=3000, targetTests=[^Homework5\.Problem1ClassTest$], loggingClasses=[java.util.logging, org.apache.log4j, org.slf4j, org.apache.commons.logging, org.apache.logging.log4j], verbose=true, failWhenNoMutations=false, outputs=[HTML, PITCLIPSE_MUTATIONS, PITCLIPSE_SUMMARY], groupConfig=TestGroupConfig [excludedGroups=[], includedGroups=[]], fullMutationMatrix=false, mutationUnitSize=0, shouldCreateTimestampedReports=true, detectInlinedCode=false, exportLineCoverage=false, mutationThreshold=0, testStrengthThreshold=0, coverageThreshold=0, mutationEngine=gregor, javaExecutable=null, includeLaunchClasspath=true, properties={}, maxSurvivors=-1, excludedRunners=[], includedTestMethods=[], testPlugin=junit, useClasspathJar=false, skipFailingTests=false]

10:19:22 AM PIT >> FINE : System class path is C:\Users\Owner_2\.p2\pool\plugins\org.pitest_1.6.8.v20230330-0839;C:\Users\Owner_2\.p2\pool\plugins\org.pitest.pitclipse.runner_2.2.1.v20230330-0839.jar;C:\Users\Owner_2\.p2\pool\plugins\org.pitest.pitclipse.runner_2.2.1.v20230330-0839.jar\target/classes;C:\Users\Owner_2\.p2\pool\plugins\org.pitest_1.6.8.v20230330-0839\lib\pitest.jar;C:\Users\Owner_2\.p2\pool\plugins\org.pitest_1.6.8.v20230330-0839\lib\pitest-entry.jar;C:\Users\Owner_2\.p2\pool\plugins\org.pitest_1.6.8.v20230330-0839\lib\pitest-command-line.jar;C:\Users\Owner_2\.p2\pool\plugins\org.pitest_1.6.8.v20230330-0839\lib\pitest-html-report.jar;C:\Users\Owner_2\.p2\pool\plugins\org.pitest.pitclipse.listeners_2.2.1.v20230330-0839.jar;C:\Users\Owner_2\.p2\pool\plugins\org.pitest.pitclipse.listeners_2.2.1.v20230330-0839.jar\target/classes;\\DISKSTATION\Family_Folder\John\Eclipse workspace\CSE 5321 2020 Fall\bin;C:\Users\Owner_2\.p2\pool\plugins\org.junit_4.13.2.v20211018-1956.jar;C:\Users\Owner_2\.p2\pool\plugins\org.hamcrest.core_1.3.0.v20180420-1519.jar;\\DISKSTATION\Family_Folder\John\Eclipse workspace\JUnitParams-1.0.4.jar;\\DISKSTATION\Family_Folder\John\Eclipse workspace\easymock-3.4.jar

10:19:22 AM PIT >> FINE : Maximum available memory is 4078 mb




    On Saturday, February 3, 2024 at 10:18:20 AM CST, John Robb ***@***.***> wrote:  
 
  Here is the longer error message:

10:17:17 AM PIT >> FINE : Coverage generator Minion exited ok

10:17:17 AM PIT >> INFO : Calculated coverage in 0 seconds.

10:17:17 AM PIT >> FINE : Used memory after coverage calculation 42 mb

10:17:17 AM PIT >> FINE : Free Memory after coverage calculation 213 mb

Exception in thread "main" java.lang.IllegalArgumentException: Illegal base64 character 3c

 at java.base/java.util.Base64$Decoder.decode0(Base64.java:848)

 at java.base/java.util.Base64$Decoder.decode(Base64.java:566)

 at java.base/java.util.Base64$Decoder.decode(Base64.java:589)

 at org.pitest.mutationtest.incremental.ObjectOutputStreamHistoryStore.deserialize(ObjectOutputStreamHistoryStore.java:124)

 at org.pitest.mutationtest.incremental.ObjectOutputStreamHistoryStore.restoreClassPath(ObjectOutputStreamHistoryStore.java:112)

 at org.pitest.mutationtest.incremental.ObjectOutputStreamHistoryStore.initialize(ObjectOutputStreamHistoryStore.java:84)

 at org.pitest.mutationtest.tooling.MutationCoverage.runAnalysis(MutationCoverage.java:159)

 at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:139)

 at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:125)

 at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:52)

 at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:98)

 at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)

 at org.pitest.pitclipse.runner.PitRunner.apply(PitRunner.java:35)

 at org.pitest.pitclipse.runner.PitRunner.apply(PitRunner.java:1)

 at java.base/java.util.Optional.map(Optional.java:260)

 at org.pitest.pitclipse.runner.PitRunnerMain.main(PitRunnerMain.java:38)




    On Saturday, February 3, 2024 at 10:14:54 AM CST, John Robb ***@***.***> wrote:  
 
  The JDK I am using is Eclipse Adoptium 21.0.2.13.
The file works with JUnit 4 and with EclEmma 3.1.7.2023... and gets complete coverage
    On Saturday, February 3, 2024 at 10:10:11 AM CST, Lorenzo Bettini ***@***.***> wrote:  
 
 


Java version, project encoding, etc.

**Comment by LorenzoBettini** [comment]
The exception comes from Java deserialization; maybe something has changed in Java 21. Note that Java 21 is not yet supported by Pitclipse.

**Comment by john-h-robb** [comment]
I had the very same problem with a much earlier JDK version 1.18 I think Lorenzo
    On Saturday, February 3, 2024 at 10:37:47 AM CST, Lorenzo Bettini ***@***.***> wrote:  
 
 


The exception comes from Java deserialization; maybe something has changed in Java 21. Note that Java 21 is not yet supported by Pitclipse.

**Comment by john-h-robb** [comment]
I also notice that it always cites the illegal character of 3c which in ascii codes is the left angle bracket "<"
    On Saturday, February 3, 2024 at 10:37:47 AM CST, Lorenzo Bettini ***@***.***> wrote:  
 
 


The exception comes from Java deserialization; maybe something has changed in Java 21. Note that Java 21 is not yet supported by Pitclipse.

**Comment by LorenzoBettini** [comment]
Maybe related to this https://github.com/hcoles/pitest/issues/521#issuecomment-425729887

**Comment by john-h-robb** [comment]
I have search my entire hard drive and network drive there is no such file as pitHistory.txt
Let's just close this and would you please delete this issue as it has some personal information in it? Thank you Lorenzo
    On Saturday, February 3, 2024 at 11:22:57 AM CST, Lorenzo Bettini ***@***.***> wrote:  
 
 


Maybe related to this hcoles/pitest#521 (comment)

**Comment by john-h-robb** [comment]
can you delete please? Thank you
    On Saturday, February 3, 2024 at 11:40:03 AM CST, Lorenzo Bettini ***@***.***> wrote:  
 
 


Closed #222 as completed.

**Comment by LorenzoBettini** [comment]
I don't have the ownership rights to delete issues in this repository. You can delete your single comments I guess
