### ISSUE TITLE
Too Slow on Eclipse

### ISSUE THREAD

**Issue by zhifanl** [pitest/pitclipse#223]
## Bug description

Running Pitest on Eclipse for a school project with < 500 lines of code and it took us 10minutes. And it didn't even give a decent summary in another developer's laptop.

## Expected behavior
Faster loading time, shorter wait time to wait for the PIT summary

## Additional context

- **Pitclipse version**:
- **Eclipse IDE version**:

**Comment by LorenzoBettini** [comment]
That depends on how many tests you have, what mutators you enable, etc. when using mutation testing you must restrict the scope of what you apply it to. Without further information I'm going to close this.

**Comment by echebbi** [comment]
@zhifanl thanks for reporting; would it be possible for you to also share the code of your school project and the version of the Eclipse IDE you're using so that the issue can be reproduced?
