### ISSUE TITLE
Automate deployment

### ISSUE THREAD

**Issue by echebbi** [pitest/pitclipse#79]
## Motivation

Pitclipse currently requires manual deployment in order to be available through its update site. This makes harder to provide updates and can thus slow down releases.

## Possible solution

We can overcome this by automating the deployment. For instance, Travis CI could be configured to deploy a new update site each time a tag is pushed to the master branch.

Additionally, we could turn the existing update site into a [composite one](https://wiki.eclipse.org/Equinox/p2/Composite_Repositories_(new)) so that we could provide several versions at once, such as:
- a snapshot version based on the last commit
- the latest release
- all previous releases

## Implementation

Travis CI can be configured thanks to the `.travis.yml` file; login and password can be encrypted through the Web UI.

The following blog posts show how a composite update site can be created and deployed to Bintray with Maven:
- [http://www.lorenzobettini.it/2015/01/creating-p2-composite-repositories-during-the-build/](http://www.lorenzobettini.it/2015/01/creating-p2-composite-repositories-during-the-build/)
- [http://www.lorenzobettini.it/2016/02/publish-an-eclipse-p2-composite-repository-on-bintray/](http://www.lorenzobettini.it/2016/02/publish-an-eclipse-p2-composite-repository-on-bintray/)

@philglover what is the current process to deploy a new version of Pitclipse?

**Comment by philglover** [comment]
It was manual upload to an S3 bucket.  @hcoles can grant you access I think.

I did briefly look into having Travis deploy to S3 a few years ago but it did require some S3 admin to do.  From having had a look at the docs again, it seems a little more intuitive than it did at the time.

Can I just say for the public record, the work and effort you have done @echebbi has been fantastic.  Thanks for picking this project up and bringing new life to it.

**Comment by philglover** [comment]
Aha, just re-read things.  Yes publishing to bintray is also a good approach.

http://eclipse.pitest.org/release/ points at the S3 bucket - I assume again @hcoles  can point eclipse.pitest.org to bintray.

**Comment by hcoles** [comment]
@philglover I assume I can too, although I have no memory of how I set this all up.

**Comment by echebbi** [comment]
@philglover thank you for the acknowledgment, it is very much appreciated! I believe using Bintray would be way more convenient because I already have the snippets for creating and uploading composite update sites. That being said, I will take a look at S3.

@hcoles I'll keep you updated on my choice between S3 and Bintray; we'll see at that time what needs to be done exactly.

**Comment by echebbi** [comment]
Hi @hcoles, I just deployed the new `2.0.0` release to https://dl.bintray.com/kazejiyu/Pitclipse/updates/, do you think that you could redirect http://eclipse.pitest.org/release/ to this address?

**Comment by hcoles** [comment]
To be honest not sure. Just looked at what I setup for the current update site many many years ago.

I currently have a CNAME record that points eclipse.pitest.org to an S3 bucket. The rest of the site is hosted on github pages.

If bintray supports it, and you can tell me what the value should be, I can add a CNAME for the new update site. Otherwise I think we'd need some sort of html hackery on guthub pages.

**Comment by echebbi** [comment]
That's unfortunate. According to [Bintray's documentation](https://jfrog.com/knowledge-base/how-to-configure-a-custom-cname-in-bintray/) adding a CNAME 1) would require a Premium account and 2) is unavailable for `dl.bintray.com` URLs.

@hcoles considering uploading to the S3 bucket instead, could you grant me the access?

@philglover the main reason why I'd like to keep the update site on http://eclipse.pitest.org/release/ is because that's the link you specified in the Eclipse Marketplace. Would you mind either changing the update site URL to point to Bintray or granting me the editing rights? Looks like it's possible at the very bottom of the `Edit` tab in [Pitclipse's product page](https://marketplace.eclipse.org/content/pitclipse):

<div align="center">
<img src="https://user-images.githubusercontent.com/25926433/66255716-365a4e80-e787-11e9-8767-149534122caa.png"/>
</div>

**Comment by echebbi** [comment]
@hcoles, @philglover and I managed to update the Eclipse Marketplace so that it now points to Bintray, hence I believe that this issue is solved and that you don't have to bother with the S3 bucket.

**Comment by hcoles** [comment]
@echebbi Excellent, I'll stop trying to remember how to administer S3.

**Comment by LorenzoBettini** [comment]
@echebbi so is http://eclipse.pitest.org/release/ containing the new releases from now on?

**Comment by echebbi** [comment]
@LorenzoBettini new releases will be published on https://dl.bintray.com/kazejiyu/Pitclipse/updates/

**Comment by LorenzoBettini** [comment]
@echebbi thanks! I see it's also in the main README (sorry, I had missed that).
