### ISSUE TITLE
Log4j2 packages should be excluded by default

### ISSUE THREAD

**Issue by LorenzoBettini** [pitest/pitclipse#91]
## Motivation

Currently, the launch configuration excludes by default the following packages `java.util.logging, org.apache.log4j, org.slf4j, org.apache.commons.logging` but in Log4j2 the package for logging is different: `org.apache.logging.log4j`, and you get survived mutants when removing Log4j2 logging statements.

## Proposed Solution

`org.apache.logging.log4j` should be excluded as well by default.

I'll try to provide a PR

**Comment by LorenzoBettini** [comment]
I was wondering if we could have a new release with this change

**Comment by echebbi** [comment]
I should have the time to release a new version by tomorrow

**Comment by echebbi** [comment]
@LorenzoBettini I just release Pitclipse 2.0.1 which should include this improvement.
